Agile Project Guidelines
HeadspringLabs/building-the-better-way pull request #10
Opened 2020-10-09 23:27 UTC by westbaymonument

Creation of the Agile Project Guidelines section folder and index.md page for Better Way, along with the initial .md page on Agile Implementation Challenges, as discussed with Adam and requested by Adam and V for Q3. @garoyeri volunteered to take a look at this, and more pages will follow next week...just getting something out there to ensure docs and folders are structured and displaying as expected.

2020-10-13 01:33 UTC, garoyeri requested changes

2020-10-13 01:33 UTC, garoyeri commented on docs/agile-project-guidelines/agile-implementation-challenges/agile-implementation-challenges.md
> +In many companies, it is often the case that the only practice that’s consistent is that no practice is consistently implemented. Every company, department, and team has its own internal languages an
The spacing around the hyphenated part is inconsistent. The last two sentences are unclear (switch to active voice). Avoid using "sacred" to avoid religious implication (even though it is a correct observation).

Results of initiatives to change these highly regarded aspects of a company, especially when instituted abruptly or without the right planning and communication, can range from unfortunate to disastrous. More often than not, the original process itself is to blame.

2020-10-13 01:33 UTC, garoyeri commented on docs/agile-project-guidelines/agile-implementation-challenges/agile-implementation-challenges.md
> +What people forget in the aftermath is that the process doesn’t choose itself: Companies create these environments, and make the decisions that lead to these results. The methodology chosen might not
Companies => companies
Should we make "agile" or "Agile" the consistent way to name this?

2020-10-13 01:33 UTC, garoyeri commented on docs/agile-project-guidelines/agile-implementation-challenges/agile-implementation-challenges.md
> +Here, we aim to identify and explore the most common explanations companies give for Agile failing upon arrival, and uncover potential root causes for a company’s split from Agile. As mentioned earli
Instead of hyphenating the last sentence, split into two sentences.

2020-10-13 01:33 UTC, garoyeri commented on docs/agile-project-guidelines/agile-implementation-challenges/agile-implementation-challenges.md
> +### Creating a business case that secures buy-in
YAAAAAAAAAAAS.

2020-10-13 01:33 UTC, garoyeri commented on docs/agile-project-guidelines/agile-implementation-challenges/agile-implementation-challenges.md
> +When pulling together any business case, the questions “Why?” and “How much?” are king. The bottom line is often the focus, so make sure it is understood how introducing agile practices to an organiz
king => absolutely critical

This paragraph starts to use the imperative. Should we have that sooner in the document? Should we write this entirely as if addressing the reader? Or reference some sort of "implementation team"?

2020-10-13 01:33 UTC, garoyeri commented on docs/agile-project-guidelines/agile-implementation-challenges/agile-implementation-challenges.md
> +- **Vision Check:** Use VTO and culture to guide decisions. How does this tie back to vision and goals? Does it move the company closer to where it is going?
What is VTO?

2020-10-13 01:33 UTC, garoyeri commented on docs/agile-project-guidelines/agile-implementation-challenges/agile-implementation-challenges.md
> +- **Up Front Contract:** The team member bringing forth the business case should state the purpose and outcome of the presentation upfront so that those listening know what the specific ask is. (i.e.
Make a clear request of the team: what is needed today?

2020-10-13 01:33 UTC, garoyeri commented on docs/agile-project-guidelines/agile-implementation-challenges/agile-implementation-challenges.md
> +With these thoughts in mind, take note: *Nothing will kill the adoption of Agile—or any major organizational shift—faster than a poorly-executed and under-communicated rollout*, regardless of a compa
use commas instead of hyphens

2020-10-13 01:33 UTC, garoyeri commented on docs/agile-project-guidelines/agile-implementation-challenges/agile-implementation-challenges.md
> +Many encounter this exact scenario in their careers: A plan is delivered to a small group from on high, which cascades down as gospel delivered from person to person throughout the company. Departmen
Avoid using "gospel". Depending on how the person views religious text, they may misunderstand your meaning. Some people may interpret that as the opposite of what you intend.

2020-10-13 01:33 UTC, garoyeri commented on docs/agile-project-guidelines/agile-implementation-challenges/agile-implementation-challenges.md
> +-Form a RACI matrix in a spreadsheet, with roles as column headers and critical pre- and post-Agile methodology rollout actions as row headers
Not sure how well this renders in Jekyll, to make this a sub-bullet list, indent it and use asterisk instead of hyphen:

```
    * Form a RACI matrix
    * Mark each box
```

Repeat for any other similar list

2020-10-13 01:33 UTC, garoyeri commented on docs/agile-project-guidelines/agile-implementation-challenges/agile-implementation-challenges.md
> +Using sprint planning as an example, the prevailing guidance for Scrum teams is generaly to hold planning once a sprint, timeboxed to eight hours per one-month sprint. That doesn’t mean sprint planni
generaly => generally

2020-10-13 01:33 UTC, garoyeri commented on docs/agile-project-guidelines/agile-implementation-challenges/agile-implementation-challenges.md
> +When meetings become inefficient, remember that Agile Scrum ceremonies are for the benefit of—and owned by—the team. As such, the team always has the power to change their format.
commas instead of hyphens

2020-10-13 01:33 UTC, garoyeri commented on docs/agile-project-guidelines/agile-implementation-challenges/agile-implementation-challenges.md
> +- **DO** align with leadership on delivery expectations and practices (see Chalenge 1 above!)
Chalenge => Challenge

2020-10-13 01:33 UTC, garoyeri commented on docs/agile-project-guidelines/agile-implementation-challenges/agile-implementation-challenges.md
> +- **CONSIDER** inviting only those necessary (notes may be shared with interested—but non-critical—parties)
commas instead of hyphens

2020-10-13 01:33 UTC, garoyeri commented on docs/agile-project-guidelines/agile-implementation-challenges/agile-implementation-challenges.md
> +- **AVOID** processes that don't work for the sake of appeasing leadership
processes for the sake of appeasing leadership that don't work

2020-10-13 01:33 UTC, garoyeri commented on docs/agile-project-guidelines/index.md
> +Companies from all industries still operate in traditional ways that are not conducive to adaptability and speed. In order to stay competitive in shifting markets, organizations are embracing Agile T
Comma instead of hyphen: It's not just about technology, it's a new way of thinking

2020-10-13 01:33 UTC, garoyeri commented on docs/agile-project-guidelines/index.md
> +Within the financial industry, technologies and expectations are changing faster than ever, and with new players entering the fray, speed and adaptability are keys to maintaining industry leadership.
hyphen => space

2020-10-13 17:16 UTC, westbaymonument reviewed
I've implemented nearly everything, I think, for both files with comments! Future docs forthcoming will be sure to take a closer look at these suggestions to avoid similar errors.

2020-10-13 17:17 UTC, westbaymonument commented
@garoyeri Thank you so much for the awesome feedback! I left a comment for all changes made (except one or two where I jumped the gun).

2020-10-13 18:18 UTC, westbaymonument commented on docs/agile-project-guidelines/agile-implementation-challenges/agile-implementation-challenges.md
> +When pulling together any business case, the questions “Why?” and “How much?” are king. The bottom line is often the focus, so make sure it is understood how introducing agile practices to an organiz
Oh, I didn't change king, but it was also a point of emphasis...I did address the flip-flopping of language / tone (direct vs. indirect).

2020-10-13 18:20 UTC, westbaymonument commented on docs/agile-project-guidelines/agile-implementation-challenges/agile-implementation-challenges.md
> +-Form a RACI matrix in a spreadsheet, with roles as column headers and critical pre- and post-Agile methodology rollout actions as row headers
I just realized they were missing spaces after; I made them match the ones below, which was what had been done with other pages already on Better Way. The bullets should show properly now.

2020-10-13 18:31 UTC, westbaymonument reviewed
Found a couple of stragglers due to collapsed comments from Garo in the thread. Got them addressed.

2020-10-14 05:36 UTC, garoyeri requested changes
It reads a lot better since you moved away from the imperative mood, it feels more generally applicable. A few small tweaks marked up (or down) below (or is it above?).

2020-10-14 05:36 UTC, garoyeri commented on docs/agile-project-guidelines/agile-implementation-challenges/agile-implementation-challenges.md
> +- Known Project Risks: Potentiavtol impediments and their planned mitigations
Potentiavtol => Potential

2020-10-14 05:36 UTC, garoyeri commented on docs/agile-project-guidelines/index.md
>  Agile Transformaion and Project Guidelines
Transformaion => Transformation

2020-10-14 05:36 UTC, garoyeri commented on docs/agile-project-guidelines/agile-implementation-challenges/agile-implementation-challenges.md
> +Many remember the game Telephone from childhood: one person thinks of a phrase and whispers it to the next person in a line, and so on until the last person in the line relates the phrase as he or sh
"he or she" => "they" (can go more gender neutral)

2020-10-19 15:47 UTC, westbaymonument reviewed
Made suggested changes from @garoyeri

2020-10-19 15:48 UTC, westbaymonument commented on docs/agile-project-guidelines/agile-implementation-challenges/agile-implementation-challenges.md
> +Many remember the game Telephone from childhood: one person thinks of a phrase and whispers it to the next person in a line, and so on until the last person in the line relates the phrase as he or sh
resolved!

2020-10-19 15:48 UTC, westbaymonument commented on docs/agile-project-guidelines/index.md
>  Agile Transformaion and Project Guidelines
resolved!

2020-10-19 15:48 UTC, westbaymonument commented on docs/agile-project-guidelines/agile-implementation-challenges/agile-implementation-challenges.md
> +- Known Project Risks: Potentiavtol impediments and their planned mitigations
this super weird issue has been resolved!

2020-10-29 19:50 UTC, westbaymonument reviewed
Updated!

2020-11-03 02:55 UTC, garoyeri requested changes
Flows a lot better now, pointing out some formatting concerns and a few random points.

2020-11-03 02:55 UTC, garoyeri commented on docs/agile-project-guidelines/agile-implementation-challenges/agile-implementation-challenges.md
> +- Project History: Background and reasons behind the rollout initiative
To maintain consistent formatting with the sections above, make the title of each list item **bold**

2020-11-03 02:55 UTC, garoyeri commented on docs/agile-project-guidelines/agile-implementation-challenges/agile-implementation-challenges.md
> +Project Artifacts: Links and shared resources the rollout team will need
Should this line be part of the list items as well? It's missing the leading ` - `

2020-11-03 02:55 UTC, garoyeri commented on docs/agile-project-guidelines/agile-implementation-challenges/agile-implementation-challenges.md
> +Not everyone will be thrilled with the organizational change, but the beauty here is that not everyone *has* to be thrilled. The team's role as an agent of change isn’t to please everyone, but to *gu
"The team's role as an agent of change..." => "The rollout team's role as an agent of change..."
I had to scroll up because I wasn't sure which team you meant here.

2020-11-03 02:55 UTC, garoyeri commented on docs/agile-project-guidelines/agile-implementation-challenges/agile-implementation-challenges.md
> +- If an organization uses multiple document management solutions, pick one location only to minimize confusion, unless otherwise required by the company
It should also be the solution most commonly used by the company (don't pick the "weird" option because it has cool features or you hate Microsoft. Pick the option that has the least cognitive friction for people to avoid giving them an excuse.

2020-11-19 15:53 UTC, westbaymonument commented on docs/agile-project-guidelines/agile-implementation-challenges/agile-implementation-challenges.md
> +- Project History: Background and reasons behind the rollout initiative
Changes applied.

2020-11-19 15:54 UTC, westbaymonument commented on docs/agile-project-guidelines/agile-implementation-challenges/agile-implementation-challenges.md
> +Project Artifacts: Links and shared resources the rollout team will need
Corrected.

2020-11-19 15:54 UTC, westbaymonument commented on docs/agile-project-guidelines/agile-implementation-challenges/agile-implementation-challenges.md
> +Not everyone will be thrilled with the organizational change, but the beauty here is that not everyone *has* to be thrilled. The team's role as an agent of change isn’t to please everyone, but to *gu
"The rollout team's role" flows strangely. I'll find another way to word.

2020-11-19 15:59 UTC, westbaymonument commented on docs/agile-project-guidelines/agile-implementation-challenges/agile-implementation-challenges.md
> +- If an organization uses multiple document management solutions, pick one location only to minimize confusion, unless otherwise required by the company
Revised the following line to make it more clear.

2020-11-19 16:00 UTC, westbaymonument commented
@garoyeri All changes requested have been made.

2020-11-20 02:51 UTC, garoyeri approved these changes

2020-11-20 02:52 UTC, garoyeri commented
I think we're good! LGTM

2020-11-20 15:57 UTC, merged