Update Versioning Tool Guidelines
HeadspringLabs/building-the-better-way pull request #13
Opened 2021-04-27 22:31 UTC by pmcvtm

Issues with [GitVersion](https://github.com/GitTools/GitVersion) on several projects last year and the enthusiastic adoption of [MinVer](https://github.com/adamralph/minver) on several others led us to reconsider our versioning tool guidelines. In the intervening months, the [offending GV bug](https://github.com/GitTools/GitVersion/issues/2074#event-3970289947) was fixed, but we still want to have our guidelines reflect _the better way_.

This PR:

- highlights MinVer as the favored way to version applications, over GitVersion or less automated processes
- still includes GitVersion as a _consideration_ when a "full" no-touch-auto-incrementing version is ideal / worth the extra configuration
- updates versioning sections per the new contextual info
- fixes some typos I saw

2021-04-28 12:41 UTC, garoyeri commented
I like the changes (especially fixing my old typos). One thing I think is important to highlight that you mentioned in passing is this: MinVer is recommended for library projects or other projects where the version number needs to be more predictable. GitVersion is recommended for top level applications where the version number is mostly decorative or informational. MinVer gives you a LOT more control and predictability in the version that's generated, given that you take the time to make the tag properly. GitVersion is hands off (as you said), but *could* produce colliding version numbers.

Also, what's your opinion on including the short Git hash in the version?

2021-04-29 15:22 UTC, pmcvtm commented
Agreed that the most important factors for making the choice should be highlighted. I was trying to keep close to the existing format / headings but maybe it could use a restructure, since we are changing the recommendation fundamentally. I'll do some shuffling and add some emphasis!

For the git hash, I typically haven't, but I can see how it'd be useful in some contexts (thinking like... build #'s when you might interactive rebase to a height that already exists?) but if it's something other folks are doing on the reg we should definitely give it a mention why or when! What do you think?

2021-04-30 18:28 UTC, garoyeri commented
It's worth a "Consider" to mention why you would and how to do it. I added it to Contoso in our Azure DevOps that way since it was already in there to put the hash in the footer and it's helpful to demonstrate that something has changed.

2021-05-03 18:29 UTC, garoyeri requested changes
Just one feedback point on spelling. Otherwise, I think it's complete.

2021-05-03 18:29 UTC, garoyeri commented on docs/development-guidelines/build-scripts/phases-of-a-build-script.md
> +[MinVer](https://github.com/adamralph/minver#readme) is a simple tool that generates a SemVer-compliant version number at build-time based on Git history. When building a particular Git revision with
"code reversions" => "code versions"

2021-05-04 14:37 UTC, pmcvtm commented on docs/development-guidelines/build-scripts/phases-of-a-build-script.md
> +[MinVer](https://github.com/adamralph/minver#readme) is a simple tool that generates a SemVer-compliant version number at build-time based on Git history. When building a particular Git revision with
Good catch, I was dancing between revisions and versions and tripped. Surprised there aren't any "visions" or "versios" in there too. Fixed!

2021-05-04 14:42 UTC, garoyeri approved these changes

2021-05-04 14:54 UTC, merged